name: GitHub Pages deploy
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'WooCommerce version (defaults to latest release in repository)'
        required: false
        default: ''

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  verify:
    name: Verify if a rebuild is needed
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest-version.outputs.version }}
      rebuild: ${{ steps.check-if-built.outputs.rebuild }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        fetch-depth: 0
    - name: Fetch latest release version if not provided
      id: get-latest-version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_VERSION: ${{ github.event.inputs.version }}
      run: |
        if [ -z "$INPUT_VERSION" ]; then
          VERSION=$(gh release view --repo "$GITHUB_REPOSITORY_OWNER/woocommerce" --json tagName -q .tagName)
        else
          VERSION="$INPUT_VERSION"
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Check if build is necessary
      id: check-if-built
      env:
        VERSION: ${{ steps.get-latest-version.outputs.version }}
      run: |
        if git tag -l "pages-deploy/${VERSION}" | grep -q .; then
            echo "rebuild=false" >> $GITHUB_OUTPUT
        else
            echo "rebuild=true" >> $GITHUB_OUTPUT
        fi

  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: verify
    if: ${{ needs.verify.outputs.rebuild == 'true' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2.34.1
      with:
        php-version: '8.1'
        tools: composer:v2
    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      run: composer install --prefer-dist
    - name: Build
      run: |
        ./deploy.sh --build-only -s ${{ needs.verify.outputs.version }} -r "$GITHUB_REPOSITORY_OWNER/woocommerce"
    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
      with:
        path: build/api
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
    - name: Tag deployed version
      run: |
        git tag "pages-deploy/${{ needs.verify.outputs.version }}"
        git push origin "pages-deploy/${{ needs.verify.outputs.version }}"
