name: GitHub Pages deploy
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'WooCommerce version (defaults to latest release in repository)'
        required: false
        default: ''
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # v2.34.1
      with:
        php-version: '8.1'
        tools: composer:v2
    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      run: composer install --prefer-dist
    - name: Fetch latest release version if not provided
      id: get-latest-version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_VERSION: ${{ github.event.inputs.version }}
      run: |
        if [ -z "$INPUT_VERSION" ]; then
          VERSION=$(gh release view --repo "$GITHUB_REPOSITORY_OWNER/woocommerce" --json tagName -q .tagName)
        else
          VERSION="$INPUT_VERSION"
        fi

        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Build
      run: |
        ./deploy.sh --build-only -s ${{ steps.get-latest-version.outputs.version }} -r "$GITHUB_REPOSITORY_OWNER/woocommerce"
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@59173cb633d9a3514f5f4552a6a3e62c6710355c # v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: gh-pages
        build_dir: build/api
